name: ansi_parser
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.2.0
  petitparser: ^5.4.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  lints: ^2.0.0
  test: ^1.21.0
